site_name: Foe Foundry
site_description: Foe Foundry helps GMs instantly summon unforgettable monsters for 5E and other fantasy TTRPGs. Skip the statblock grind—get handcrafted powers, flavorful foes, and encounter-ready creations built by a GM, for GMs.

nav:
  - Monsters: monsters/index.md
  - Families: families/index.md
  - Generator: generate.md
  - Powers: powers/all.md
  - Blog: blog/index.md
  - Topics: topics/index.md

use_directory_urls: true

site_url: !ENV [SITE_URL]

hooks:
  - docs_gen/my_hooks.py

plugins:
  - search
  - gen-files:
      scripts:
        - scripts/gen_pages.py
  - blogging:
      dirs:
        - blog
      features:
        tags:
          insert: bottom
          index_page: blog/tags.md

theme:
  name: mkdocs
  custom_dir: docs_theme/
  analytics:
    gtag: !ENV [GTAG]

extra_css:
  - css/site.css

extra_javascript:
  - scripts/extras.js

markdown_extensions:
  - admonition
  - tables
  - attr_list
  - toc:
      permalink: true
  - foe_foundry_data.markdown
