site_name: Foe Foundry

nav:
  - Monsters: monsters/index.md
  - Families: families/index.md
  - Blog: blog/index.md
  - Topics: topics/index.md
  - Credits: credits.md

use_directory_urls: true

site_url: https://foefoundry.com

hooks:
  - docs_hooks/my_hooks.py

plugins:
  - search
  - gen-files:
      scripts:
        - scripts/gen_pages.py
  - blogging:
      dirs:
        - blog
      features:
        tags:
          insert: bottom
          index_page: blog/tags.md

theme:
  name: mkdocs
  custom_dir: docs_theme/

extra_css:
  - css/branding.css
  - css/pamphlet.css
  - css/parchment.css
  - css/root.css
  - css/statblock.css
  - css/tooltips.css

markdown_extensions:
  - admonition
  - tables
  - attr_list
  - toc:
      permalink: true
  - foe_foundry.markdown
