site_name: Foe Foundry
site_description: Foe Foundry helps GMs instantly summon unforgettable monsters for 5E and other fantasy TTRPGs. Skip the statblock grind—get handcrafted powers, flavorful foes, and encounter-ready creations built by a GM, for GMs.
site_url: !ENV [SITE_URL]
site_author: Evan Rash

nav:
  - Generate: generate.md
  - Monsters:
      - All Monsters: monsters/index.md
      - Orcs & Goblins: families/orcs_and_goblinoids.md
      - Undead: families/undead.md
      - Villains: families/villains.md
      - Rivals: families/rivals.md
  - Powers: powers/all.md
  - Learn:
      - Blog: blog/index.md
      - Topics: topics/index.md
      - RSS: rss.xml

use_directory_urls: true

hooks:
  - docs_gen/my_hooks.py

plugins:
  - search
  - gen-files:
      scripts:
        - scripts/gen_pages.py
  - blogging:
      dirs:
        - blog
      features:
        tags:
          insert: bottom
          index_page: blog/tags.md
  - rss:
      image: image/icons/favicon.png
      feed_description: The latest monsters, features, and blog posts from Foe Foundry - a monster generator that helps you summon unforgettable foes instantly. Built by a GM, for GMs.
      length: 100
      feeds_filenames:
        json_created: feed.json
        json_updated: feed_updated.json
        rss_created: rss.xml
        rss_updated: rss_updated.xml
      match_path: ^blog/(?!index\.md$|tags\.md$).+
      url_parameters:
        utm_source: "rss"
  - open-in-new-tab:
      add_icon: True
  - minify:
      cache_safe: true
      minify_css: true
      css_files:
        - css/site.css
      js_files:
        - scripts/extras.js
theme:
  name: mkdocs
  custom_dir: docs_theme/
  analytics:
    gtag: !ENV [GTAG]

extra_css:
  - css/site.css

extra_javascript:
  - scripts/extras.js

markdown_extensions:
  - admonition
  - tables
  - attr_list
  - toc:
      permalink: true
  - foe_foundry_data.markdown
