[tool.poetry]
name = "foe-foundry"
version = "0.1.0"
description = "Programmatically create 5E foes using Forge of Foes"
authors = ["Evan Rash <evanrash@gmail.com>"]
license = "CC BY 4"
readme = "README.md"
packages = [{include = "foe_foundry"}]

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.25.0"
d20 = "^1.1.2"
jinja2 = "^3.1.2"
num2words = "^0.5.12"
pandas = "^2.0.3"
markdown = "^3.4.4"
jinja-markdown = "^1.210911"
click = "^8.1.7"
beautifulsoup4 = "^4.12.2"
tqdm = "^4.66.1"
selenium = "^4.13.0"
pillow = "^10.0.1"
fastapi = "^0.104.0"
uvicorn = {extras = ["standard"], version = "^0.23.2"}

[tool.poetry.group.dev.dependencies]
pytest = "^7.0"
flake8 = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
