[tool.poetry]
name = "foe-foundry"
version = "0.1.0"
description = "Programmatically create 5E foes using Forge of Foes"
authors = ["Evan Rash <evanrash@gmail.com>"]
license = "CC BY 4"
readme = "README.md"
packages = [{include = "foe_foundry"}]

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.25.0"
d20 = "^1.1.2"
jinja2 = "^3.1.2"
num2words = "^0.5.12"
pandas = "^2.0.3"

[tool.poetry.group.dev.dependencies]
pytest = "^7.0"
flake8 = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
