import './components/SvgIcon';
import './components/MonsterRating';
import './components/MonsterArt';
import './components/PowerLoadout';
import './components/MonsterInfo';
import './components/MonsterCard';
import './components/MonsterBuilder';
import './pages/generator';
import './pages/generator_v2';
