name: Build and Test

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10.15
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.15

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.2
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Run build script
        run: |
          chmod +x ./scripts/build_site.sh
          ./scripts/build_site.sh

      - name: Run tests
        run: poetry run pytest
