name: Unit Tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      SITE_URL: http://128.0.0.1:8000

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10.15
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.15

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.2
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Run tests
        run: poetry run pytest