name: Unit Tests

on:
  pull_request:
    branches: ["*"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      SITE_URL: http://128.0.0.1:8000

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install npm dependencies
        run: npm ci

      - name: Set up Python 3.13.7
        uses: actions/setup-python@v5
        with:
          python-version: 3.13.7

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.1.3
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Setup Site
        run: |
          chmod +x ./scripts/build_site.sh
          ./scripts/build_site.sh

      - name: Run tests
        run: poetry run pytest